spring.application.name=provider-ms-01


server.port=7071

spring.application.instance-id=${spring.application.name}:${random.value}


#register with eureka server
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka